Fixed problems with importing classes from their header, which caused an 'undefined reference to' error to come up. Also removed all 'using namespace Utils' so that other files that import those files won't 'use' namespace Utils.